apiVersion: v1
kind: Service
metadata:
  name: uptime-postgres
  labels:
    app.kubernetes.io/name: uptime-postgres
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: uptime-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
